os: linux
dist: focal
language: generic
services:
  - docker

jobs:
  include:
    - stage: SmartvovLezModelUFD build and run
      script:
      - |
        cd SmartGovLezModelUFD
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build --no-cache -t smartgov:lez-model-ufd Context
        echo "################################################### start of run"
        docker run --mount type=bind,src="$PWD/output",dst="/Output" -t smartgov:lez-model-ufd ./static_config_lez.properties 100
    - stage: SmartvovLezModel build and run
      script:
      - |
        cd SmartGovLezModel
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build --no-cache -t smartgov:lez-model Context
        echo "################################################### start of run"
        mkdir output && chmod 777 output
        docker run --mount type=bind,src="$PWD/output",dst="/Output" -t smartgov:lez-model static_config_lez.properties 100
    - stage: LezViewer build (no run)
      script:
      - |
        cd LezViewer
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build --no-cache -t smartgov:lez-viewer Context
